### ISSUE TITLE
Browse posts and pages do not return `reading_time` when using `fields` parameter

### ISSUE THREAD

**Issue by maveric1977** [TryGhost/SDK#261]
### Issue Summary

Browse requests for posts and pages do not return `reading_time` when using `fields` parameter.

### To Reproduce

1. Send a get request including the fields parameter:

```
curl 'https://GHOST_URL/ghost/api/v3/content/posts/?key=API_KEY&fields=id%2Cslug%2Ctitle%2Creading_time' \
  -H 'Accept: application/json'
```

The response does not include `reading_time`, although the same request without the `fields` parameter returns the `reading_time`.

### Technical details:

* Ghost Version: 3.12.1
* Node Version: 10.19.0
* Browser/OS: Ubuntu 16.04.6 LTS
* Database: mySQL

**Comment by gmfmi** [comment]
I got the exact same issue with v3.16.1 (latest stable), using both CLI installer and Docker.

Probably related to: https://github.com/TryGhost/Ghost/issues/10396.

**Comment by ErisDS** [comment]
This issue is actually [this bug](https://github.com/TryGhost/Ghost/issues/10396#issuecomment-803591643) and nothing to do with the SDK tools.

I have reopened https://github.com/TryGhost/Ghost/issues/10396#issuecomment-803591643 and left a comment explaining the workaround and what will happen next. Please read that comment and if you have further input please reply on that issue.
