### ISSUE TITLE
Excerpt not returned when used in fields

### ISSUE THREAD

**Issue by thenitai** [TryGhost/SDK#375]
### Issue Summary

The excerpt is not returned in fields

### To Reproduce

api.posts.browse({fields : 'excerpt'})....

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

api.posts.browse() will return the excerpt.

### Technical details:

* Ghost Version: 4.x (latest as of today)
* Node Version: 12
* Browser/OS: macOS / Ubuntu
* Database: MySQL / local

**Comment by ErisDS** [comment]
This issue is actually [this bug](https://github.com/TryGhost/Ghost/issues/10396#issuecomment-803591643) and nothing to do with the SDK tools.

I have reopened https://github.com/TryGhost/Ghost/issues/10396#issuecomment-803591643 and left a comment explaining the workaround and what will happen next. Please read that comment and if you have further input please reply on that issue.
